// Estrutura comum: head, cabeçalho, rodapé, botão flutuante e páginas auxiliares.
import { site } from './site.mjs';

export const escape = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const arrow = `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>`;

const consentHead = `<script>(function(){var c=null;try{c=localStorage.getItem('consentimento')}catch(e){}window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}window.__consent=c;gtag('consent','default',{analytics_storage:c==='aceito'?'granted':'denied',ad_storage:c==='aceito'?'granted':'denied',ad_user_data:c==='aceito'?'granted':'denied',ad_personalization:c==='aceito'?'granted':'denied',wait_for_update:500});})();</script>`;
const gtmId = 'GTM-MBMG5FC8';
const tagManagerHead = `<!-- Google Tag Manager --><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${gtmId}');</script><!-- End Google Tag Manager -->`;
const tagManagerBody = `<!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${gtmId}" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!-- End Google Tag Manager (noscript) -->`;

export const whatsappUrl = (text = site.whatsappText) => `https://wa.me/${site.whatsapp}?text=${encodeURIComponent(text)}`;

// Marca: símbolo (balão com curva de crescimento) + nome. O símbolo é o mesmo do favicon.
export const mark = `<svg class="brand-mark" viewBox="0 0 64 64" aria-hidden="true"><path d="M16 6h32a12 12 0 0 1 12 12v22a12 12 0 0 1-12 12H26L13 61v-9.5A12 12 0 0 1 4 40V18A12 12 0 0 1 16 6z" fill="#1fb85a"/><path d="M16 38l10-10 8 8 14-14" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M39 22h9v9" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
export const brand = `${mark}<span class="brand-name">otimizza<span>.digital</span></span>`;

const whatsappGlyph = `<svg viewBox="0 0 32 32" aria-hidden="true" fill="currentColor"><path d="M16 2a14 14 0 0 0-12.1 21L2 30l7.2-1.9A14 14 0 1 0 16 2Zm0 25.4a11.3 11.3 0 0 1-5.8-1.6l-.4-.2-4.2 1.1 1.1-4.1-.3-.5A11.4 11.4 0 1 1 16 27.4Zm6.3-8.5c-.3-.2-1.9-.9-2.2-1s-.5-.2-.7.2-.8 1-1 1.2-.4.2-.7 0a9.3 9.3 0 0 1-4.5-3.9c-.3-.5.3-.5.9-1.7.1-.2 0-.4 0-.6l-1-2.4c-.3-.6-.6-.5-.8-.5h-.6c-.2 0-.6.1-.8.4s-1.1 1.1-1.1 2.6 1.1 3 1.3 3.2 2.3 3.6 5.5 5c2 .8 2.8.9 3.8.7.6-.1 1.9-.8 2.2-1.5s.3-1.3.2-1.5-.2-.2-.5-.4Z"/></svg>`;

const igIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>`;
const fbIcon = `<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M13.5 22v-8h2.7l.4-3.2h-3.1V8.8c0-.9.3-1.6 1.6-1.6h1.7V4.4c-.3 0-1.3-.1-2.5-.1-2.5 0-4.1 1.5-4.1 4.2v2.3H7.4V14h2.8v8z"/></svg>`;
function socialLinks() {
  const itens = [site.instagram && `<a href="${escape(site.instagram)}" target="_blank" rel="noopener noreferrer" aria-label="Instagram da Otimizza Digital">${igIcon}<span>@otimizza_digital</span></a>`, site.facebook && `<a href="${escape(site.facebook)}" target="_blank" rel="noopener noreferrer" aria-label="Facebook da Otimizza Digital">${fbIcon}<span>Facebook</span></a>`].filter(Boolean);
  return itens.length ? `<div class="footer-social">${itens.join('')}</div>` : '';
}
function header() {
  return `<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Otimizza Digital — início">${brand}</a><nav class="site-nav" aria-label="Seções"><a href="#como-funciona">Como funciona</a><a href="#painel">Painel</a><a href="#plano">Plano</a><a href="#duvidas">Dúvidas</a><a href="/ajuda/">Guia</a></nav><a class="header-login" href="https://app.otimizza.digital/login" target="_blank" rel="noopener noreferrer" aria-label="Entrar no painel do Cardápio IA"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4M10 17l5-5-5-5M15 12H3"/></svg><span>Entrar</span></a><a class="header-cta" href="${escape(whatsappUrl())}" target="_blank" rel="noopener noreferrer">${whatsappGlyph}<span>Falar no WhatsApp</span></a></div></header>`;
}

function cookieNotice() {
  return `<div class="cookie-notice" id="aviso-cookies" hidden role="region" aria-label="Aviso de cookies"><p>Usamos cookies de medição (Google Analytics) e de anúncios (Meta Pixel) para entender o uso do site e divulgar o Cardápio IA. Você escolhe. <a href="/privacidade/">Saiba mais</a>.</p><div class="cookie-actions"><button type="button" class="cookie-essencial" data-consent="recusado">Só o essencial</button><button type="button" class="cookie-aceitar" data-consent="aceito">Aceitar</button></div></div>`;
}
function footer() {
  return `<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a class="brand" href="/" aria-label="Otimizza Digital — início">${brand}</a><p>Cardápio e atendimento com inteligência artificial no WhatsApp para restaurantes, lanchonetes e similares.</p></div><div class="footer-contact"><a href="/ajuda/">Guia de implantação</a><a href="https://app.otimizza.digital/login" target="_blank" rel="noopener noreferrer">Entrar no painel</a><a href="#" data-cookie-prefs>Preferências de cookies</a><strong>Contato</strong><a href="${escape(whatsappUrl())}" target="_blank" rel="noopener noreferrer">WhatsApp ${site.whatsappDisplay}</a><a href="mailto:${site.email}">${site.email}</a><span>${site.city} · atendimento à cidade e região</span>${socialLinks()}</div><div class="footer-about"><strong>Quem faz</strong><a href="${site.ownerSite}/" target="_blank" rel="noopener noreferrer">${site.owner} · TA Consulting</a><span>Mais de 15 anos em marketing digital, dados e automação.</span></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} ${site.name}</span><a href="/privacidade/">Política de Privacidade</a><a href="#conteudo">Voltar ao início ${arrow}</a></div></div></footer>`;
}

function whatsappFloat() {
  return `<a class="whatsapp-float" href="${escape(whatsappUrl())}" target="_blank" rel="noopener noreferrer" aria-label="Falar com a Otimizza Digital pelo WhatsApp (abre em nova aba)"><span>Falar agora<span>WhatsApp</span></span>${whatsappGlyph}</a>`;
}

function schema(path, title, description, extra) {
  const org = site.origin + '/#organization';
  const graph = [
    { '@type': 'Organization', '@id': org, name: site.name, legalName: site.name, url: site.origin + '/', logo: { '@type': 'ImageObject', url: site.origin + '/assets/logo-otimizza-digital.png' }, email: site.email, telephone: '+' + site.whatsapp,
      address: { '@type': 'PostalAddress', addressLocality: site.cityName, addressRegion: site.region, addressCountry: site.country }, areaServed: [{ '@type': 'City', name: site.cityName }, { '@type': 'Country', name: 'Brasil' }],
      founder: { '@type': 'Person', name: site.owner, url: site.ownerSite + '/sobre/' }, contactPoint: { '@type': 'ContactPoint', contactType: 'sales', telephone: '+' + site.whatsapp, availableLanguage: 'Portuguese' }, ...(site.sameAs.length ? { sameAs: site.sameAs } : {}) },
    { '@type': 'WebSite', '@id': site.origin + '/#website', url: site.origin + '/', name: site.name, publisher: { '@id': org }, inLanguage: 'pt-BR' },
    { '@type': 'WebPage', '@id': site.origin + path, url: site.origin + path, name: title, description, inLanguage: 'pt-BR', dateModified: site.updated, isPartOf: { '@id': site.origin + '/#website' },
      breadcrumb: { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: site.origin + '/' }, ...(path !== '/' ? [{ '@type': 'ListItem', position: 2, name: title, item: site.origin + path }] : [])] } },
    ...extra,
  ];
  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph });
}

export function layout({ path = '/', title, description, body, extra = [], noindex = false }) {
  const fullTitle = title.includes(site.name) ? title : `${title} | ${site.name}`;
  const social = `${site.origin}/assets/social-cover.png`;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8">${consentHead}${tagManagerHead}<meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(fullTitle)}</title><meta name="description" content="${escape(description)}"><meta name="author" content="${site.owner}"><meta name="theme-color" content="#ffffff"><meta name="color-scheme" content="light"><meta name="robots" content="${noindex ? 'noindex,follow' : 'index,follow,max-image-preview:large'}">${path === '/404/' ? '' : `<link rel="canonical" href="${site.origin}${path}">`}<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><link rel="preload" href="/assets/fonts/barlow-semi-condensed-500.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/manrope-400.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css"><meta property="og:type" content="website"><meta property="og:site_name" content="${site.name}"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="${escape(fullTitle)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${site.origin}${path}"><meta property="og:image" content="${social}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Cardápio IA, da Otimizza Digital: seu WhatsApp atende sozinho."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(fullTitle)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${social}"><script type="application/ld+json">${schema(path, fullTitle, description, extra)}</script><script src="/assets/site.js" defer></script></head><body>${tagManagerBody}${header()}<main id="conteudo">${body}</main>${cookieNotice()}${footer()}${whatsappFloat()}</body></html>`;
}

export function privacyPage() {
  const atualizado = '09/10/2026';
  const sec = (t, html) => `<h2>${t}</h2>${html}`;
  const body = `<section class="container simple-page pp"><p class="pp-eyebrow">Política de Privacidade</p><h1>Como a Otimizza Digital<br>trata os seus dados.</h1><p class="pp-lead">Esta política explica o que coletamos, por que, com quem compartilhamos e quais são os seus direitos, em três situações: quando você visita este site, quando usa o painel do Cardápio IA e quando conversa com um restaurante atendido pelo Cardápio IA no WhatsApp. Segue a Lei Geral de Proteção de Dados (Lei 13.709/2018).</p>
<nav class="pp-nav" aria-label="Seções"><a href="#quem">1. Quem somos</a><a href="#site">2. Site</a><a href="#painel">3. Painel</a><a href="#whatsapp">4. Atendimento no WhatsApp</a><a href="#ia">5. Inteligência artificial</a><a href="#compartilhamento">6. Compartilhamento</a><a href="#seguranca">7. Segurança e retenção</a><a href="#direitos">8. Seus direitos</a><a href="#cookies">9. Cookies</a><a href="#mudancas">10. Mudanças</a></nav>
${sec('<span id="quem">1. Quem somos</span>', `<p>${site.name}, ${site.city}, Brasil, responsável por este site e pelo produto Cardápio IA. Encarregado de dados (DPO): ${site.owner}. Contato para qualquer assunto desta política: <a href="mailto:${site.email}">${site.email}</a> ou WhatsApp <a href="https://wa.me/${site.whatsapp}" target="_blank" rel="noopener noreferrer">${site.whatsappDisplay}</a>.</p>`)}
${sec('<span id="site">2. Quando você visita o site (otimizza.digital)</span>', `<ul>
<li><strong>Dados técnicos de acesso</strong> (endereço IP, navegador, páginas acessadas, data e hora), registrados pela hospedagem (Vercel) para funcionamento e segurança. Base legal: legítimo interesse. Retenção: a da hospedagem, em geral poucos dias.</li>
<li><strong>Medição de audiência</strong> com Google Analytics 4, carregado pelo Google Tag Manager: páginas vistas, origem da visita e cliques nos botões de WhatsApp, com identificadores anônimos. Só é ativada após o seu aceite no aviso de cookies. Base legal: consentimento.</li>
<li><strong>Medição de anúncios</strong> com o Meta Pixel (Facebook e Instagram), também carregado pelo Tag Manager, para medir campanhas e formar públicos de anúncio. Só após o aceite. Base legal: consentimento.</li>
<li><strong>Contato pelo WhatsApp</strong>: os botões abrem o WhatsApp com uma mensagem preparada; você decide se envia. A conversa comercial é tratada pela Otimizza para responder ao seu pedido. Base legal: execução de medidas pré-contratuais.</li></ul>`)}
${sec('<span id="painel">3. Quando você usa o painel (app.otimizza.digital)</span>', `<p>O painel é usado por restaurantes clientes. Coletamos <strong>e-mail, nome e senha</strong> (guardada apenas em formato cifrado) para o acesso, e registramos <strong>data do último acesso</strong>. Os dados do restaurante (cardápio, horários, bairros, entregadores, telefones da equipe) são informados pelo próprio cliente para o funcionamento do serviço. O painel usa um cookie de sessão, estritamente necessário, que não exige consentimento. A conta de demonstração pública não coleta dados pessoais; tudo nela é fictício e apagado diariamente.</p>`)}
${sec('<span id="whatsapp">4. Quando você conversa com um restaurante atendido pelo Cardápio IA</span>', `<p>Se você é cliente de um restaurante que usa o Cardápio IA, o atendente automático responde no número do restaurante. Nessa relação, <strong>o restaurante é o controlador</strong> dos seus dados e <strong>a Otimizza é a operadora</strong>, tratando os dados em nome dele e conforme as instruções dele, nos termos do contrato de prestação de serviço.</p><ul>
<li><strong>Dados tratados</strong>: número de telefone, nome exibido no WhatsApp, mensagens de texto, áudios (convertidos em texto para atendimento), endereço de entrega, bairro, itens pedidos, valores, forma de pagamento, histórico de pedidos e anotações da equipe do restaurante.</li>
<li><strong>Finalidade</strong>: mostrar o cardápio, anotar e confirmar o pedido, calcular taxa e previsão, avisar a cozinha e o entregador, enviar o status do pedido, passar a conversa para uma pessoa quando solicitado e gerar relatórios ao restaurante.</li>
<li><strong>O que não fazemos</strong>: não processamos pagamentos (Pix, cartão e dinheiro seguem com o restaurante), não vendemos dados, não usamos as conversas para publicidade e não enviamos mensagens em massa.</li>
<li><strong>Como pedir exclusão ou acesso</strong>: fale com o restaurante ou escreva para <a href="mailto:${site.email}">${site.email}</a> informando o número de telefone; atendemos em nome do restaurante.</li></ul>`)}
${sec('<span id="ia">5. Uso de inteligência artificial</span>', `<p>As mensagens são interpretadas por modelos de linguagem de fornecedores especializados (atualmente Anthropic, por meio da plataforma OpenRouter) e os áudios são transcritos pela Groq. Esses fornecedores recebem o conteúdo necessário para responder e, pelos seus termos de API, não usam os dados para treinar modelos. Preços, totais, números de pedido e disponibilidade nunca são decididos pela IA: vêm do cadastro do restaurante. A IA pode errar; por isso o restaurante confirma cada pedido e pode assumir a conversa a qualquer momento.</p>`)}
${sec('<span id="compartilhamento">6. Com quem compartilhamos</span>', `<ul>
<li><strong>Restaurante contratante</strong>: todos os dados da conversa e do pedido, pois o atendimento é dele.</li>
<li><strong>Entregadores do restaurante</strong>: endereço, telefone e forma de pagamento do pedido que vão entregar.</li>
<li><strong>Fornecedores de tecnologia</strong>, como operadores sob contrato: hospedagem e infraestrutura (servidor próprio e Vercel), WhatsApp/Meta (transporte das mensagens), Anthropic e OpenRouter (modelo de linguagem), Groq (transcrição de áudio), Google e Meta (medição do site, mediante consentimento). Alguns ficam fora do Brasil; a transferência internacional segue as garantias da LGPD.</li>
<li><strong>Sistemas do restaurante</strong> (PDV ou ERP), quando o restaurante ativa a integração, no padrão Open Delivery ou por webhook.</li>
<li><strong>Autoridades</strong>, quando exigido por lei ou ordem judicial.</li></ul>`)}
${sec('<span id="seguranca">7. Segurança e retenção</span>', `<p>Dados trafegam cifrados (HTTPS) e ficam em servidor com acesso restrito por chave, firewall e cópias de segurança diárias. Senhas são armazenadas com hash. Conversas e pedidos ficam guardados enquanto o restaurante for cliente, para histórico e relatórios, e são apagados em até 30 dias após o encerramento do contrato, salvo obrigação legal de guarda. O restaurante pode pedir a exclusão de uma conversa específica a qualquer momento. Em caso de incidente de segurança com risco relevante, comunicaremos a ANPD e os afetados conforme a lei.</p>`)}
${sec('<span id="direitos">8. Seus direitos</span>', `<p>Você pode pedir confirmação de tratamento, acesso, correção, anonimização, bloqueio ou eliminação, portabilidade, informação sobre compartilhamento, e revogar o consentimento. Escreva para <a href="mailto:${site.email}">${site.email}</a>. Respondemos em até 15 dias. Se não ficar satisfeito, você pode recorrer à Autoridade Nacional de Proteção de Dados (ANPD).</p>`)}
${sec('<span id="cookies">9. Cookies</span>', `<p>Sem o seu aceite, o site guarda apenas a sua escolha sobre cookies, no próprio navegador. Com o aceite, Google e Meta gravam cookies de medição pelos prazos definidos por eles (em geral até 13 meses no Google Analytics e 90 dias no Meta Pixel). Para mudar a escolha use o link “Preferências de cookies” no rodapé ou apague os cookies do site no navegador. O painel usa apenas o cookie de sessão necessário ao login.</p>`)}
${sec('<span id="mudancas">10. Mudanças nesta política</span>', `<p>Podemos atualizar este texto quando o serviço mudar. A versão vigente é sempre a publicada em <a href="${site.origin}/privacidade/">${site.origin.replace('https://', '')}/privacidade</a>, com a data abaixo. Mudanças relevantes para os clientes serão avisadas por e-mail ou pelo painel.</p>`)}
<p class="simple-updated">Última atualização: ${atualizado}.</p></section>`;
  return layout({ path: '/privacidade/', title: 'Política de Privacidade', description: 'Política de privacidade da Otimizza Digital e do Cardápio IA: dados do site, do painel e do atendimento no WhatsApp, uso de IA, compartilhamento, retenção e direitos pela LGPD.', body });
}

export function notFoundPage() {
  return layout({ path: '/404/', title: 'Página não encontrada', description: 'Esta página não existe no site da Otimizza Digital.', noindex: true, body: `<section class="container simple-page"><h1>Essa página não existe.</h1><p>Volte ao <a href="/">início</a> ou fale com a gente pelo <a href="${escape(whatsappUrl())}" target="_blank" rel="noopener noreferrer">WhatsApp</a>.</p></section>` });
}
